//
// Generated file, do not edit! Created by opp_msgtool 6.1 from inet/applications/tcpapp/ModbusResponseHeader.msg.
//

#ifndef __INET_MODBUSRESPONSEHEADER_M_H
#define __INET_MODBUSRESPONSEHEADER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class ModbusResponseHeader;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>inet/applications/tcpapp/ModbusResponseHeader.msg:8</tt> by opp_msgtool.
 * <pre>
 * class ModbusResponseHeader extends FieldsChunk
 * {
 *     chunkLength = B(12);
 *     uint16_t transactionId;
 *     uint16_t protocolId;
 *     uint16_t length;
 *     uint8_t slaveId;
 *     uint8_t functionCode;
 * }
 * </pre>
 */
class INET_API ModbusResponseHeader : public ::inet::FieldsChunk
{
  protected:
    uint16_t transactionId = 0;
    uint16_t protocolId = 0;
    uint16_t length = 0;
    uint8_t slaveId = 0;
    uint8_t functionCode = 0;

  private:
    void copy(const ModbusResponseHeader& other);

  protected:
    bool operator==(const ModbusResponseHeader&) = delete;

  public:
    ModbusResponseHeader();
    ModbusResponseHeader(const ModbusResponseHeader& other);
    virtual ~ModbusResponseHeader();
    ModbusResponseHeader& operator=(const ModbusResponseHeader& other);
    virtual ModbusResponseHeader *dup() const override {return new ModbusResponseHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual uint16_t getTransactionId() const;
    virtual void setTransactionId(uint16_t transactionId);

    virtual uint16_t getProtocolId() const;
    virtual void setProtocolId(uint16_t protocolId);

    virtual uint16_t getLength() const;
    virtual void setLength(uint16_t length);

    virtual uint8_t getSlaveId() const;
    virtual void setSlaveId(uint8_t slaveId);

    virtual uint8_t getFunctionCode() const;
    virtual void setFunctionCode(uint8_t functionCode);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ModbusResponseHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ModbusResponseHeader& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::ModbusResponseHeader *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::ModbusResponseHeader*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_MODBUSRESPONSEHEADER_M_H

