//
// Generated file, do not edit! Created by opp_msgtool 6.1 from inet/applications/tcpapp/OperatorRequest.msg.
//

#ifndef __INET_OPERATORREQUEST_M_H
#define __INET_OPERATORREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class OperatorRequest;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>inet/applications/tcpapp/OperatorRequest.msg:9</tt> by opp_msgtool.
 * <pre>
 * class OperatorRequest extends FieldsChunk
 * {
 *     string targetHostName;
 *     uint16_t transactionId;
 *     uint16_t protocolId;
 *     uint16_t length;
 *     uint8_t slaveId;
 *     uint8_t functionCode;
 *     uint16_t startAddress;
 *     uint16_t quantity;
 * 
 * }
 * </pre>
 */
class INET_API OperatorRequest : public ::inet::FieldsChunk
{
  protected:
    ::omnetpp::opp_string targetHostName;
    uint16_t transactionId = 0;
    uint16_t protocolId = 0;
    uint16_t length = 0;
    uint8_t slaveId = 0;
    uint8_t functionCode = 0;
    uint16_t startAddress = 0;
    uint16_t quantity = 0;

  private:
    void copy(const OperatorRequest& other);

  protected:
    bool operator==(const OperatorRequest&) = delete;

  public:
    OperatorRequest();
    OperatorRequest(const OperatorRequest& other);
    virtual ~OperatorRequest();
    OperatorRequest& operator=(const OperatorRequest& other);
    virtual OperatorRequest *dup() const override {return new OperatorRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getTargetHostName() const;
    virtual void setTargetHostName(const char * targetHostName);

    virtual uint16_t getTransactionId() const;
    virtual void setTransactionId(uint16_t transactionId);

    virtual uint16_t getProtocolId() const;
    virtual void setProtocolId(uint16_t protocolId);

    virtual uint16_t getLength() const;
    virtual void setLength(uint16_t length);

    virtual uint8_t getSlaveId() const;
    virtual void setSlaveId(uint8_t slaveId);

    virtual uint8_t getFunctionCode() const;
    virtual void setFunctionCode(uint8_t functionCode);

    virtual uint16_t getStartAddress() const;
    virtual void setStartAddress(uint16_t startAddress);

    virtual uint16_t getQuantity() const;
    virtual void setQuantity(uint16_t quantity);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OperatorRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OperatorRequest& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::OperatorRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::OperatorRequest*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_OPERATORREQUEST_M_H

