//
// Generated file, do not edit! Created by opp_msgtool 6.1 from inet/applications/modbusapp/ListMsg.msg.
//

#ifndef __INET_LISTMSG_M_H
#define __INET_LISTMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class ListMsg;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/applications/base/ApplicationPacket_m.h" // import inet.applications.base.ApplicationPacket


namespace inet {

/**
 * Class generated from <tt>inet/applications/modbusapp/ListMsg.msg:9</tt> by opp_msgtool.
 * <pre>
 * class ListMsg extends FieldsChunk
 * {
 *     chunkLength = B(5);
 *     uint32_t sequenceNumber;
 *     bool ifList = true;
 * }
 * </pre>
 */
class INET_API ListMsg : public ::inet::FieldsChunk
{
  protected:
    uint32_t sequenceNumber = 0;
    bool ifList = true;

  private:
    void copy(const ListMsg& other);

  protected:
    bool operator==(const ListMsg&) = delete;

  public:
    ListMsg();
    ListMsg(const ListMsg& other);
    virtual ~ListMsg();
    ListMsg& operator=(const ListMsg& other);
    virtual ListMsg *dup() const override {return new ListMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual uint32_t getSequenceNumber() const;
    virtual void setSequenceNumber(uint32_t sequenceNumber);

    virtual bool getIfList() const;
    virtual void setIfList(bool ifList);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ListMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ListMsg& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::ListMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::ListMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_LISTMSG_M_H

