//
// Generated file, do not edit! Created by opp_msgtool 6.1 from inet/applications/modbusapp/ModbusHeader.msg.
//

#ifndef __INET_MODBUSHEADER_M_H
#define __INET_MODBUSHEADER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class ModbusHeader;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>inet/applications/modbusapp/ModbusHeader.msg:8</tt> by opp_msgtool.
 * <pre>
 * class ModbusHeader extends FieldsChunk
 * {
 *     chunkLength = B(7);
 *     uint16_t transactionId;
 *     uint16_t protocolId;
 *     uint16_t length;
 *     uint8_t slaveId;
 * //    uint8_t functionCode;      
 * //    uint16_t startAddress;                            
 * //    uint16_t quantity; 
 * 
 * }
 * </pre>
 */
class INET_API ModbusHeader : public ::inet::FieldsChunk
{
  protected:
    uint16_t transactionId = 0;
    uint16_t protocolId = 0;
    uint16_t length = 0;
    uint8_t slaveId = 0;

  private:
    void copy(const ModbusHeader& other);

  protected:
    bool operator==(const ModbusHeader&) = delete;

  public:
    ModbusHeader();
    ModbusHeader(const ModbusHeader& other);
    virtual ~ModbusHeader();
    ModbusHeader& operator=(const ModbusHeader& other);
    virtual ModbusHeader *dup() const override {return new ModbusHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual uint16_t getTransactionId() const;
    virtual void setTransactionId(uint16_t transactionId);

    virtual uint16_t getProtocolId() const;
    virtual void setProtocolId(uint16_t protocolId);

    virtual uint16_t getLength() const;
    virtual void setLength(uint16_t length);

    virtual uint8_t getSlaveId() const;
    virtual void setSlaveId(uint8_t slaveId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ModbusHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ModbusHeader& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::ModbusHeader *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::ModbusHeader*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_MODBUSHEADER_M_H

